### ISSUE TITLE
Experience

### ISSUE THREAD

**Issue by dhruvabhat24** [dhruvabhat24/Leetcode-2024#151]
# You can add some lines of your choise anything else you want to share else start answering the questions.
1. What initially motivated you to contribute to the [Leetcode-2024](https://github.com/dhruvabhat24/Leetcode-2024) project? Did the experience meet your expectations?

2. What aspect of the contribution process, from guidelines to code review, did you find most helpful? Conversely, what could be improved to streamline the contributor experience?

3. Did you encounter any specific challenges while contributing? If so, how did you overcome them, and would you be willing to share your learnings with the community?

## tag Dhruva Bhat on your post

**Comment by Abiji-2020** [comment]
It was a good experience as contributing this repo let me share my full response in linkedIn

**Comment by dhruvabhat24** [comment]
> It was a good experience as contributing this repo let me share my full response in linkedIn 

Thankyou.

**Comment by pradyumna100903** [comment]
This was my first time contributing to any repo's and got to learn many new things while contributing to open source. Detailed Review Response will be shared in LinkedIn Soon! Thanks!

**Comment by dhruvabhat24** [comment]
> This was my first time contributing to any repo's and got to learn many new things while contributing to open source. Detailed Review Response will be shared in LinkedIn Soon! Thanks!

Thankyou
